import { Octokit } from '@octokit/rest';

export async function exportToGitHub(
  token: string,
  owner: string,
  repoName: string,
  files: Record<string, string>,
  projectName: string
): Promise<string> {
  const octokit = new Octokit({ auth: token });

  let repo;
  try {
    const response = await octokit.repos.createForAuthenticatedUser({
      name: repoName,
      description: `Generated by Lovable-lite: ${projectName}`,
      private: false,
      auto_init: true,
    });
    repo = response.data;
  } catch {
    const response = await octokit.repos.get({ owner, repo: repoName });
    repo = response.data;
  }

  const refResponse = await octokit.git.getRef({
    owner,
    repo: repoName,
    ref: `heads/${repo.default_branch}`,
  });
  const latestCommitSha = refResponse.data.object.sha;

  const baseTreeResponse = await octokit.git.getCommit({
    owner,
    repo: repoName,
    commit_sha: latestCommitSha,
  });
  const baseTreeSha = baseTreeResponse.data.tree.sha;

  const treeItems = await Promise.all(
    Object.entries(files).map(async ([path, content]) => {
      const blobResponse = await octokit.git.createBlob({
        owner,
        repo: repoName,
        content: Buffer.from(content).toString('base64'),
        encoding: 'base64',
      });
      return {
        path,
        mode: '100644' as const,
        type: 'blob' as const,
        sha: blobResponse.data.sha,
      };
    })
  );

  const newTreeResponse = await octokit.git.createTree({
    owner,
    repo: repoName,
    base_tree: baseTreeSha,
    tree: treeItems,
  });

  const newCommitResponse = await octokit.git.createCommit({
    owner,
    repo: repoName,
    message: `feat: Export from Lovable-lite - ${projectName}`,
    tree: newTreeResponse.data.sha,
    parents: [latestCommitSha],
  });

  await octokit.git.updateRef({
    owner,
    repo: repoName,
    ref: `heads/${repo.default_branch}`,
    sha: newCommitResponse.data.sha,
  });

  return repo.html_url;
}
